Update expected env file

diff --git a/scripts/dev b/scripts/dev
--- a/scripts/dev
+++ b/scripts/dev
@@ -4,14 +4,14 @@
 
 set -e
 
-if [ -f .env.dev ]; then
-  export $(grep -v '^#' ./.env.dev | xargs)
+if [ -f .env ]; then
+  export $(grep -v '^#' ./.env | xargs)
 else
-  echo ".env.dev file not found!"
+  echo ".env file not found!"
   exit 1
 fi
 
-echo "Environment variables loaded from .env.dev"
+echo "Environment variables loaded from .env"
 
 if ! command -v docker &> /dev/null; then
     echo "Docker could not be found"
@@ -20,6 +20,11 @@ fi
 
 if ! docker info &> /dev/null; then
     echo "Docker daemon is not running"
+    exit 1
+fi
+
+if ! pg_isready &> /dev/null; then
+    echo "pg_isready command not found, please install PostgreSQL client tools"
     exit 1
 fi
 
